name: "Build and push images"

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build images"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push images to Docker hub
        uses: docker/build-push-action@v4.2.1
        with:
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x
          tags: ${{ env.DOCKERHUB_REPOSITORY }}